// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: broker.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageBroker_PublishMessage_FullMethodName = "/broker.MessageBroker/PublishMessage"
	MessageBroker_ConsumeMessage_FullMethodName = "/broker.MessageBroker/ConsumeMessage"
)

// MessageBrokerClient is the client API for MessageBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageBrokerClient interface {
	PublishMessage(ctx context.Context, in *MessagePublishRequest, opts ...grpc.CallOption) (*MessagePublishResponse, error)
	ConsumeMessage(ctx context.Context, in *MessageConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageConsumeResponse], error)
}

type messageBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBrokerClient(cc grpc.ClientConnInterface) MessageBrokerClient {
	return &messageBrokerClient{cc}
}

func (c *messageBrokerClient) PublishMessage(ctx context.Context, in *MessagePublishRequest, opts ...grpc.CallOption) (*MessagePublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagePublishResponse)
	err := c.cc.Invoke(ctx, MessageBroker_PublishMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBrokerClient) ConsumeMessage(ctx context.Context, in *MessageConsumeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageConsumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageBroker_ServiceDesc.Streams[0], MessageBroker_ConsumeMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MessageConsumeRequest, MessageConsumeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageBroker_ConsumeMessageClient = grpc.ServerStreamingClient[MessageConsumeResponse]

// MessageBrokerServer is the server API for MessageBroker service.
// All implementations must embed UnimplementedMessageBrokerServer
// for forward compatibility.
type MessageBrokerServer interface {
	PublishMessage(context.Context, *MessagePublishRequest) (*MessagePublishResponse, error)
	ConsumeMessage(*MessageConsumeRequest, grpc.ServerStreamingServer[MessageConsumeResponse]) error
	mustEmbedUnimplementedMessageBrokerServer()
}

// UnimplementedMessageBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageBrokerServer struct{}

func (UnimplementedMessageBrokerServer) PublishMessage(context.Context, *MessagePublishRequest) (*MessagePublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedMessageBrokerServer) ConsumeMessage(*MessageConsumeRequest, grpc.ServerStreamingServer[MessageConsumeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ConsumeMessage not implemented")
}
func (UnimplementedMessageBrokerServer) mustEmbedUnimplementedMessageBrokerServer() {}
func (UnimplementedMessageBrokerServer) testEmbeddedByValue()                       {}

// UnsafeMessageBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBrokerServer will
// result in compilation errors.
type UnsafeMessageBrokerServer interface {
	mustEmbedUnimplementedMessageBrokerServer()
}

func RegisterMessageBrokerServer(s grpc.ServiceRegistrar, srv MessageBrokerServer) {
	// If the following call pancis, it indicates UnimplementedMessageBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageBroker_ServiceDesc, srv)
}

func _MessageBroker_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBrokerServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBroker_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBrokerServer).PublishMessage(ctx, req.(*MessagePublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBroker_ConsumeMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessageConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageBrokerServer).ConsumeMessage(m, &grpc.GenericServerStream[MessageConsumeRequest, MessageConsumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageBroker_ConsumeMessageServer = grpc.ServerStreamingServer[MessageConsumeResponse]

// MessageBroker_ServiceDesc is the grpc.ServiceDesc for MessageBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.MessageBroker",
	HandlerType: (*MessageBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMessage",
			Handler:    _MessageBroker_PublishMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConsumeMessage",
			Handler:       _MessageBroker_ConsumeMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "broker.proto",
}
